### ISSUE TITLE
Add possibility to create campaigns

### ISSUE THREAD

**Issue by Aadesh-Baral** [Aadesh-Baral/OSMLocalizer#32]
Campaigns are important to create and manage multiple challenges.
It will consist of following features:
- [ ] Allow drawing campaign AOI or upload geojson.
- [ ] Just like Tasking Manager projects the campaigns AOI should have ability to be splitted into multiple challenges under one or multiple localization theme.
- [ ] Creation of challenge templates.
- [ ] Allow campaign favorite function.
- [ ] Ability to feature Campaign.
